// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNZHzLBzyjKuc8T6cF1MDZpY10NKUpLTw',
    appId: '1:223903345853:web:dfa2101c87719f3ad69bd4',
    messagingSenderId: '223903345853',
    projectId: 'project-fb-7b60a',
    authDomain: 'project-fb-7b60a.firebaseapp.com',
    storageBucket: 'project-fb-7b60a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQpzSrqVNqDtXmZuxTKmJ4tqJAZ3AxA1Y',
    appId: '1:223903345853:android:f912fb75b45fc7d4d69bd4',
    messagingSenderId: '223903345853',
    projectId: 'project-fb-7b60a',
    storageBucket: 'project-fb-7b60a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtGJJBzt6rSDrCJ1VsR1J0hr7PF5gs2wY',
    appId: '1:223903345853:ios:9899280672e541e5d69bd4',
    messagingSenderId: '223903345853',
    projectId: 'project-fb-7b60a',
    storageBucket: 'project-fb-7b60a.appspot.com',
    iosClientId: '223903345853-66l5ina3ms206n9vsjemqtep6sui1g2t.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtGJJBzt6rSDrCJ1VsR1J0hr7PF5gs2wY',
    appId: '1:223903345853:ios:9899280672e541e5d69bd4',
    messagingSenderId: '223903345853',
    projectId: 'project-fb-7b60a',
    storageBucket: 'project-fb-7b60a.appspot.com',
    iosClientId: '223903345853-66l5ina3ms206n9vsjemqtep6sui1g2t.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseDemo',
  );
}
